---
- name: Start app
  connection: local
  ansible.builtin.uri:
    validate_certs: false
    url: https://{{ iox_base_url }}/iox/api/v2/hosting/apps/{{ app_name }}/state?action=start
    method: POST
    headers:
      X-Token-Id: "{{ auth_token }}"
    timeout: 240